learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('mainpage.urls',namespace = 'mainpage')),
    url(r'',include('users.urls',namespace = 'users')),
]

mainpage/urls.py
"""mainpage urls"""

from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^topics/$',views.topics, name = 'topics'),
	url(r'^topics/(?P<topic_id>\d+)/$',views.topic, name = 'topic'),
	url(r'^new_topic/$',views.new_topic, name = 'new_topic'),
	url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name = 'new_entry'),
	url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name = 'edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
	url(r'^login/$',login,{'template_name':'users/login.html'},name = 'login'),
	url(r'^logout/$',views.logout_view,name = 'logout'),
	url(r'^register/$',views.register,name = 'register'),
]

mainpage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	text = models.CharField(max_length = 200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)

	def __unicode__(self):
		return self.text

class Entry(models.Model):
	topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __unicode__(self):
		return self.text[:50]+"..."

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mainpage/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text':''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text':''}
		widgets = {'text': forms.Textarea(attrs={'cols':80})}

mainpage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from .models import Topic, Entry
from .forms import TopicForm,EntryForm
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
	if request.user.is_authenticated():		
		topics = Topic.objects.filter(owner = request.user).order_by('date_added')
		context = {'topics':topics}
		return render(request,'mainpage/index.html',context)
	else:
		return render(request,'mainpage/index.html')

# This is not used now
@login_required
def topics(request):
	topics = Topic.objects.filter(owner = request.user).order_by('date_added')
	context = {'topics':topics}
	return render(request,'mainpage/topics.html',context)
	

@login_required
def topic(request,topic_id):
	topics = Topic.objects.filter(owner = request.user).order_by('date_added')
	topic = get_object_or_404(Topic,id = topic_id)
#	topic = Topic.objects.get(id = topic_id)
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic, 'entries':entries, 'topics':topics}
	return render(request,'mainpage/topic.html',context)

#@login_required
def new_topic(request):
	topics = Topic.objects.filter(owner = request.user).order_by('date_added')
	if request.method != 'POST':
		form = TopicForm()
	else:
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit = False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('mainpage:topics'))
	context = {'form':form,'topics':topics}
	return render(request,'mainpage/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
	topics = Topic.objects.filter(owner = request.user).order_by('date_added')
	topic = Topic.objects.get(id = topic_id)
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data = request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('mainpage:topic',args=[topic_id]))
	context = {'topic':topic,'form':form,'topics':topics}
	return render(request,'mainpage/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
	topics = Topic.objects.filter(owner = request.user).order_by('date_added')
	entry = Entry.objects.get(id = entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404
	
	if request.method != 'POST':
		form = EntryForm(instance = entry)
		
	else: 
		form = EntryForm(instance = entry, data = request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('mainpage:topic',args=[topic.id]))
	context = {'entry':entry,'topic':topic, 'form':form,'topics':topics}
	return render(request,'mainpage/edit_entry.html',context)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('mainpage:index'))

def register(request):
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data = request.POST)

		if form.is_valid():
			new_user = form.save()
			authenticated_user = authenticate(username = new_user.username,password = request.POST['password1'])
			login(request,authenticated_user)
			return HttpResponseRedirect(reverse('mainpage:index'))
	context = {'form':form}
	return render(request,'users/register.html',context)

mainpage/templates/mainpage/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang = 'en'>
  <head>
  	<meta charset = "utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE-edge">
  	<meta name="viewpoint" content="width=device-width, initial-scale=1">

  	<title>Learning Log</title>

  	{% bootstrap_css %}
  	{% bootstrap_javascript %}

  </head>


  <body>
  	
  	<nav class = "navbar navbar-default navbar-static-top" style = "background-color: #2F4F4F;">
  		<div class = "container">
	  		<div class = "navbar-header">
	  			<button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target = "#navbar" aria-expanded = "false" aria-controls = "navbar">
	  			</button>
	  			<a class = "navbar-brand" href = "{% url 'mainpage:index' %}" style = "color: #8FBC8F;">HOME</a>

	  		</div>


	  		<div id = "navbar" class = "navbar-collapse collapse" id = "navbarNavDropdown">
	  	 		<ul class = "nav navbar-nav">
	  				<li class = "nav-item dropdown">

	  					<a class="nav-link dropdown-toggle" href="mainpage:index" id="navbarDropdownMenuLink" data-toggle="dropdown" role = "button" aria-haspopup="true" aria-expanded="false" style = "color: #8FBC8F;"><span class = "caret"></span>
	  						TOPICS
	  					</a>
	  					
					        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style = "background-color: #2F4F4F;">

					        	{% if user.is_authenticated %}

						          	{% for topic in topics %}
								       
								          <li><a class = "dropdown-item" href="{% url 'mainpage:topic' topic.id %}" style = "font-size:15px; text-transform: uppercase; color: #8FBC8F;">{{topic}}</a></li>	
					        						  								 
								    {% endfor %}	

								{% endif %}
								
					        </ul>
					   
	  				</li>
	  			</ul> 

	  			<ul class = "nav navbar-nav">
	  				{% if user.is_authenticated %}
	  					<li><a href = "{% url 'mainpage:new_topic' %}" style = "color: #8FBC8F;">NEW TOPIC</a></li>
	  				{% endif %}
	  			</ul>
	  				
	  			<ul class ="nav nav-pills navbar-right">
	  				{% if user.is_authenticated %}
	  				  <li><a style = "color: #8FBC8F;">Hello,{{user.username}}.</a></li>
	  				  <li role = "presentation;"><a href  = "{% url 'users:logout' %}" style = "color: #8FBC8F;">LOG OUT</a></li>
	  				{% else %}
	  				  <li role = "presentation;"><a href  = "{% url 'users:register' %}" style = "color: #8FBC8F;">REGISTER</a></li>
	  				  <li role = "presentation;"><a href  = "{% url 'users:login' %}" style = "color: #8FBC8F;">LOG IN</a></li>
	  				{% endif %}
	  			</ul>
	  		</div>
	  	</div>
	</nav>

	
 
 	<div class = "container">

 		<div class = "page-header">
 			{% block header %}{% endblock header %}
 		</div>

 		<div>
 			{% block content %}{% endblock content %}
 		</div>
 	</div>


 		  		<script type="text/javascript">
						  				$('ul.nav li.dropdown').hover(function() {
					  $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
					}, function() {
					  $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
					});
	  			</script> 
  </body>

mainpage/templates/mainpage/edit_entry.html
{% extends "mainpage/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1 style = "font-size: 25px;">
  	<a href = "{% url 'mainpage:topic' topic.id %}" style = "color: #000000;">{{ topic }}</a>
  </h1>
  <h2 style = "font-size: 20px;">
  	Edit entry
  </h2>
{% endblock header %}


{% block content %}

  <form action = "{% url 'mainpage:edit_entry' entry.id %}" method = 'post' class = "form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    	<button name = "submit" class = "btn btn-primary" style = "background-color: #2F4F4F;">save changes</button>
    {% endbuttons %}

  </form>

{% endblock content %}

mainpage/templates/mainpage/index.html
<!DOCTYPE html>

<body>
{% extends "mainpage/base.html" %}

{% block header %}
  <div class = "jumbotron">
  	<h1 style = "font-size:45px;text-align:left; color: #2F4F4F;">WELCOME.</h1>
  	<p class = "lead">Nobody knows who I really am, maybe they just don't give a damn.</p>
  	<p class = "lead">But if I ever need someone to come along, I know you would follow me, and keep me strong.</p>
  	<hr class = "my-4">
  	<p> Someday.</p>
  </div>
{% endblock header %}

{% block content %}
<br>
<h2 style = "font-size:20px;text-align:center;">
	<a href = "{% url 'users:register' %}" style = "color: #8FBC8F; text-align: center; border-radius: 10px; border: 2px solid #8FBC8F; padding: 10px; ">Register Here</a>
</h2>
<br>
<h2 style = "font-size:20px;text-align:center; color: #2F4F4F;">
	Start from April, treasured things.
</h2>
{% endblock content %}
</body>
</html>

mainpage/templates/mainpage/new_entry.html
{% extends "mainpage/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1 style = "font-size: 25px;">
  	<a href = "{% url 'mainpage:topic' topic.id %}" style = "color: #2F4F4F;">{{ topic }}</a>
  </h1>
  <h2 style = "font-size: 20px;">
  	Add a new entry
  </h2>
{% endblock header %}

{% block content %}

  <form action = "{% url 'mainpage:new_entry' topic.id %}" method = 'post' class = "form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    	<button name = "submit" class = "btn btn-primary" style=" background-color: #2F4F4F;">add entry</button>
    {% endbuttons %}

  </form>

  

{% endblock content %}

mainpage/templates/mainpage/new_topic.html
{% extends "mainpage/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2 style = "font-size: 20px;">Add a new topic</h2>
{% endblock header %}

{% block content %}
  
  <form action = "{% url 'mainpage:new_topic' %}" method = 'post' class = "form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
    	<button name = "submit" class = "btn btn-primary" style = "background-color: #2F4F4F;">add topic</button>
    {% endbuttons %}
    
  </form>

{% endblock content %}

mainpage/templates/mainpage/topic.html
{% extends 'mainpage/base.html' %}

{% block header %}
  <h2 style = "font-size: 25px;">{{ topic }}</h2>
{% endblock header %}

{% block content %}

<h3 style = "font-size: 20px;">Entries</h3>
  <p>
    <a href = "{% url 'mainpage:new_entry' topic.id %}" style = "color: #2F4F4F;">Add a new entry</a>
  </p>


{% for entry in entries %}

<div class = "panel panel-default">
  <div class = "panel-heading" style = "background-color: #2F4F4F;">
    <h3 style = "font-size: 20px; color: #8FBC8F;">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small>
        <a href = "{% url 'mainpage:edit_entry' entry.id %}" style = "color: #FFFFF0;">edit entry</a>
      </small>
    </h3>
  </div>

  <div class = "panel-body">
    {{ entry.text|linebreaks }}
  </div>
</div>

{% empty %}
    There is no entries for the topic.
{% endfor %}

<br>
  <h3 style = "font-size: 20px; text-align: center;">
    <a href = "{% url 'mainpage:new_entry' topic.id %}" style = "color: #8FBC8F; text-align: center; border-radius: 10px; border: 2px solid #8FBC8F; padding: 10px;">Add a new entry</a>
  </h3>

{% endblock content %}

mainpage/templates/mainpage/topics.html
<!DOCTYPE html>

{% extends "mainpage/base.html" %}
{% block header %}
  <h1 style = "font-size: 25px;">Topics</h1>
{% endblock header %}


{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3 style = "font-size: 20px;">
          <a href="{% url 'mainpage:topic' topic.id %}" style = "color: #8FBC8F;">{{topic}}</a>
        </h3>
      </li>
    {% empty %}
      <li>There is no new topic</li>
    {% endfor %}
  </ul>

<br>
<h3 style = "font-size: 20px; text-align: center;">
  <a href = "{% url 'mainpage:new_topic' %}" style = "color: #8FBC8F; text-align: center; border-radius: 10px; border: 2px solid #8FBC8F; padding: 10px;">Add a new topic</a>
</h3>

{% endblock content %}

users/templates/users/login.html
{% extends "mainpage/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2 style = "font-size: 20px;">Log into your account</h2>
{% endblock header %}

{% block content %}

<!-- delete, bootstrap can deal with errors
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again!</p>
  {% endif %}
 -->

  <form method = "post" action = "{% url 'users:login' %}" class = "form">
	  {% csrf_token %}
	  {% bootstrap_form form %}

	  {% buttons %}
	  	<button name = "submit" class = "btn btn-primary" style = "background-color: #2F4F4F;">log in</button>
	  {% endbuttons %}
	  <input type = "hidden" name = "next" value = "{% url 'mainpage:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "mainpage/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2 style = "font-size: 20px;">Register</h2>
{% endblock header %}

{% block content %}

  <form method = "post" action = "{% url 'users:register' %}" class = "form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
   		<button name = "submit" class = "btn btn-primary" style = "background-color: #2F4F4F;">register</button>
    {% endbuttons %}
  <input type = "hidden" name = "next" value = "{% url 'mainpage:index' %}" />
  </form>

{% endblock content %}